src/Entity/Statistic.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StatisticRepository")
 * @ORM\Table(name="statistics")
 */
class Statistic
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $product_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $click_number;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="statistics")
     * @ORM\JoinColumn(nullable=false,onDelete="CASCADE")
     */
    private $statistic_user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductId(): ?int
    {
        return $this->product_id;
    }

    public function setProductId(int $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }

    public function getClickNumber(): ?int
    {
        return $this->click_number;
    }

    public function setClickNumber(int $click_number): self
    {
        $this->click_number = $click_number;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatisticUser(): ?User
    {
        return $this->statistic_user;
    }

    public function setStatisticUser(?User $statistic_user): self
    {
        $this->statistic_user = $statistic_user;

        return $this;
    }
}

src/Form/StatisticType.php
<?php

namespace App\Form;

use App\Entity\Statistic;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;

class StatisticType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('product_id',IntegerType::class,array('attr' => array('min' => 1)))
            ->add('click_number',IntegerType::class,array('attr' => array('min' => 1)))
            ->add('date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Statistic::class,
        ]);
    }
}

src/Controller/Backend/BackendController.php
<?php

namespace App\Controller\Backend;


use App\Controller\BaseController;

class BackendController extends BaseController
{
    public $_theme = 'backend';

    public function adminDashboard()
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        // or add an optional message - seen by developers
        $this->denyAccessUnlessGranted('ROLE_USER', null, 'User tried to access a page without having ROLE_USER');
    }
}

src/Controller/Backend/PromotionController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Statistic;
use App\Entity\Utils;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\PromotionProducts;
use App\Entity\Promotion;
use App\Form\Promotion1Type;
use App\Helper\ArrayHelper;
use App\Repository\PromotionRepository;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/promotion")
 */
class PromotionController extends BackendController
{
    /**
     * @Route("/", name="promotion_index", methods={"GET"})
     */
    public function index(PromotionRepository $promotionRepository): Response
    {
        $condition = ['promotion_user'=> $this->getUser()];

        if($this->getUser()->hasRole('ROLE_SUPER_ADMIN')){
            $condition = [];
        }

        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findBy($condition, ['date'=> 'DESC']),
        ]);
    }


    /**
     * @Route("/new", name="promotion_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $promotion = new Promotion();
        $form = $this->createForm(Promotion1Type::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted())
        {
            $promotion->setPromotionUser($this->getUser());

            $request = $request->request;
            $promotion_product = $request->get('promotion_product');
            $product_exist = ArrayHelper::getValue($promotion_product, 'product_id.0');

            if(!isset($product_exist) || !$product_exist)
            {
                $form->addError(new FormError('You must add products'));
            }

            if($form->isValid())
            {
                $productIds = ArrayHelper::getValue($promotion_product, 'product_id');
                $note = ArrayHelper::getValue($promotion_product, 'note');

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($promotion);


                foreach ($productIds as $key => $pro)
                {
                    $pro = abs(intval($pro));
                    if(!$pro)
                    {
                        continue;
                    }

                    $noteVal = ArrayHelper::getValue($note, $key);

                    $promProduct = new PromotionProducts();
                    $promProduct->setNote($noteVal);
                    $promProduct->setProductId($pro);
                    $promProduct->setPromotion($promotion);
                    $entityManager->persist($promProduct);
                }

                $entityManager->flush();

                $this->addFlash('success', 'The promotion has been created.');

                return $this->redirectToRoute('promotion_index');
            }

        }

        return $this->render('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
            'values' => [],
        ]);
    }



    /**
     * @Route("/{id}", name="promotion_show", methods={"GET"})
     */
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="promotion_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Promotion $promotion): Response
    {
        $form = $this->createForm(Promotion1Type::class, $promotion);
        $form->handleRequest($request);


        if ($form->isSubmitted())
        {
            $request = $request->request;
            $promotion_product = $request->get('promotion_product');
            $product_exist = ArrayHelper::getValue($promotion_product, 'product_id.0');

            if(!isset($product_exist) || !$product_exist)
            {
                $form->addError(new FormError('You must add products'));
            }

            if($form->isValid())
            {
                $productIds = ArrayHelper::getValue($promotion_product, 'product_id');
                $note = ArrayHelper::getValue($promotion_product, 'note');

                foreach ($promotion->getPromotionProducts() as $val){
                    $promotion->removePromotionProduct($val);
                }

                $entityManager =  $this->getDoctrine()->getManager();

                foreach ($productIds as $key => $pro)
                {
                    $pro = abs(intval($pro));

                    if(!$pro ||  !intval($pro))
                    {
                        continue;
                    }

                    $noteVal = ArrayHelper::getValue($note, $key);

                    $promProduct = new PromotionProducts();
                    $promProduct->setNote($noteVal);
                    $promProduct->setProductId($pro);
                    $promProduct->setPromotion($promotion);
                    $entityManager->persist($promProduct);
                }

                $entityManager->flush();

                $this->addFlash('success', 'The promotion has been changed.');

                return $this->redirectToRoute('promotion_index');
            }

        }

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('promotion_index');
        }

        return $this->render('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
            'values' => $promotion->getPromotionProducts(),
        ]);
    }

    public function ajaxPromotionProducts(Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();

        if (!$request->isXmlHttpRequest()) {
            return new JsonResponse(array(
                'status' => 'Error',
                'message' => 'Error'),
                400);
        }

        if (isset($request->request)) {

            $promotion_id = $request->request->get('promotion_id');

            $promotion_id = intval($promotion_id);

            if ($promotion_id == 0)
            {
                // You can customize error messages
                // However keep in mind that this data is visible client-side
                // You shouldn't give out clues to what went wrong to potential attackers
                return new JsonResponse(array(
                    'status' => 'Error',
                    'message' => 'Error'),
                    400);
            }

            $promotionRepository = $entityManager->getRepository(Promotion::class);
            $promotion = $promotionRepository->findOneBy(array(
                'id' => $promotion_id,
//                'promotion_user' => $this->getUser()
            ));

            if ($promotion === null)
            {
                // Looks like something went wrong
                return new JsonResponse(array(
                    'status' => 'Error',
                    'message' => 'Error'),
                    400);
            }

            // All the test were perfomed, time to handle the data and perform the request
            // Which in our case means retriving the products for
            $products = $promotion->getPromotionProducts();
            // Transform data to whatever form is needed for the client side
            // In my case, I need an array with names and ids

            $products_array = array();
            $user = $this->getUser();

            foreach ($products as $product)
            {
                $productID = $product->getProductId();
                $arr=array(
                    'note' => $product->getNote(),
                    'id' => $productID,
                );


                if($user->hasRole('ROLE_SUPER_ADMIN'))
                {

                    $productRepository = $entityManager->getRepository(Promotion::class);
                    $productsClick = $productRepository::getClickByProductId($entityManager, $productID);

                    $arr['clicks'] = isset($productsClick[$product->getId()]) ? $productsClick[$product->getId()]['click'] : '';
                }

                array_push($products_array, $arr);
            }

            // Send all this back to client
            return new JsonResponse(array(
                'status' => 'OK',
                'role_admin' => $user->hasRole('ROLE_SUPER_ADMIN') ? true : false,
                'message' => $products_array),
                200);
        }
    }

    /**
     * @Route("/{id}", name="promotion_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Promotion $promotion): Response
    {
        if ($this->isCsrfTokenValid('delete' . $promotion->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($promotion);
            $entityManager->flush();
        }

        $this->addFlash('success', 'The promotion has been deleted.');

        return $this->redirectToRoute('promotion_index');
    }


}

src/Controller/Backend/StatisticController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Promotion;
use App\Entity\PromotionProducts;
use App\Entity\Statistic;
use App\Entity\Utils;
use App\Form\Promotion1Type;
use App\Form\StatisticType;
use App\Helper\ArrayHelper;
use App\Repository\StatisticRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/statistic")
 */
class StatisticController extends BackendController
{

    /**
     * @Route("/", name="statistic_index", methods={"GET"})
     */
    public function index(StatisticRepository $statisticRepository): Response
    {
        return $this->render('statistic/index.html.twig', [
            'statistics' => $statisticRepository->findAll(),
        ]);
    }

    /**
     * @Route("/add", name="statistic_add", methods={"GET","POST"})
     */
    public function add(Request $request): Response
    {
        $statistic = new Statistic();
        $form = $this->createForm(StatisticType::class, $statistic);
        $form->handleRequest($request);

        if ($form->isSubmitted())
        {
            $entityManager = $this->getDoctrine()->getManager();

            $getStatistic = $request->request->get('statistic');
            $product_id = $getStatistic['product_id'];
            $promotionRepository = $entityManager->getRepository(PromotionProducts::class);
            $promotionProd = $promotionRepository->findBy(array(
                'product_id' => $product_id
            ),['id'=> 'DESC']);

            if(!$promotionProd){
                $form->addError(new FormError('Product id isn\'t exists'));
            }


            if($form->isValid())
            {
                $statistic->setStatisticUser($this->getUser());
                $entityManager->persist($statistic);
                $entityManager->flush();

                $this->addFlash('success', 'The statistic has been added.');

                return $this->redirectToRoute('promotion_index');
            }
        }

        return $this->render('statistic/new.html.twig', [
            'statistic' => $statistic,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="statistic_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Statistic $statistic): Response
    {
        if ($this->isCsrfTokenValid('delete'.$statistic->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($statistic);
            $entityManager->flush();
        }

        return $this->redirectToRoute('statistic_index');
    }

}

templates/backend/statistic/_delete_form.html.twig
<form method="post" action="{{ path('statistic_delete', {'id': statistic.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ statistic.id) }}">
    <button class="btn"><i class="fa fa-trash"></i></button>
</form>

templates/backend/statistic/_form.html.twig
{{ form_start(form) }}

<div class="build-form-parent">

    {% if not form.vars.valid %}
        <div class="alert alert-danger">
            {{ form_errors(form) }}
        </div>
    {% endif %}

    <div class="form-group row">
        <label for="inputName" class="col-sm-1 col-form-label">Product Id</label>
        <div class="col-sm-11">
            {{ form_widget(form.product_id, {'attr': {'id':'inputName', 'class': 'form-control', "placeholder": 'Product Id'}}) }}
            <div class="form-error">
                {{ form_errors(form.product_id) }}
            </div>
        </div>

    </div>

    <div class="form-group row">
        <label for="inputName" class="col-sm-1 col-form-label">Click Number</label>
        <div class="col-sm-11">
            {{ form_widget(form.click_number, {'attr': {'id':'inputName', 'class': 'form-control', "placeholder": 'Click Number'}}) }}
            <div class="form-error">
                {{ form_errors(form.click_number) }}
            </div>
        </div>

    </div>

    <div class="form-group row">
        <label for="inputName" class="col-sm-1 col-form-label">Date</label>
        <div class="col-sm-11">
            {{ form_widget(form.date, {'attr': {'id':'inputName', 'class': 'form-control', "placeholder": 'Date'}}) }}
            <div class="form-error">
                {{ form_errors(form.date) }}
            </div>
        </div>

    </div>

    {{ form_row(form._token) }}

    <button class="btn btn-success new-promotion">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/backend/statistic/index.html.twig
{% extends 'backend/layouts/main.html.twig' %}

{% block title %}Statistic index{% endblock %}

{% block content %}

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <h1>Statistic index</h1>

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Product_id</th>
                            <th>Click_number</th>
                            <th>Date</th>
                            <th>actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for statistic in statistics %}
                            <tr>
                                <td>{{ statistic.id }}</td>
                                <td>{{ statistic.productId }}</td>
                                <td>{{ statistic.clickNumber }}</td>
                                <td>{{ statistic.date ? statistic.date|date('Y-m-d') : '' }}</td>
                                <td>
                                    {{ include('backend/statistic/_delete_form.html.twig') }}
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="5">no records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </section>
{% endblock %}

templates/backend/statistic/new.html.twig
{% extends 'backend/layouts/main.html.twig' %}

{% block content %}

    <div class="card-body">
        <title>Add Statistic</title>

        <h2 class="add-title">Add new Statistic</h2>

        {{ include('backend/statistic/_form.html.twig') }}

    </div>

{% endblock %}